server:
  port: 1009

#eureka.instance.preferIpAddress=true
# 考虑安全性,配置Eureka访问密码
spring:
  security:
    basic:
      enabled: true
    user:
      name: zbpk
      password: 19941016jin
  application:
    name: zbpk-eureka-service
  jmx:
    default-domain: zbpk-eureka-service
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance-id:${server.port}}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:${server.port}/eureka/


  server:  #配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
    eviction-interval-timer-in-ms: 5000





